### ISSUE TITLE
Error during build phase

### ISSUE THREAD

**Issue by raphael10-collab** [geocine/ultralight-react#1]
(base) marco@pc01:~/webMatters/Ultralight/ultralight-react/app$ yarn
    yarn install v1.22.5
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    info fsevents@2.3.2: The platform "linux" is incompatible with this module.
    info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
    info fsevents@1.2.12: The platform "linux" is incompatible with this module.
    info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
    [3/4] Linking dependencies...
    warning " > @testing-library/user-event@12.7.0" has unmet peer dependency "@testing-library/dom@>=7.21.4".
    [4/4] Building fresh packages...
    Done in 11.42s.

    (base) marco@pc01:~/webMatters/Ultralight/ultralight-react/app$ cd ..

    (base) marco@pc01:~/webMatters/Ultralight/ultralight-react$ mkdir build

    (base) marco@pc01:~/webMatters/Ultralight/ultralight-react$ cd build/

    (base) marco@pc01:~/webMatters/Ultralight/ultralight-react/build$ cmake ..
    -- The C compiler identification is GNU 9.3.0
    -- The CXX compiler identification is GNU 9.3.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/marco/webMatters/Ultralight/ultralight-react/build

    (base) marco@pc01:~/webMatters/Ultralight/ultralight-react/build$ cmake --build . --config Release
    (base) marco@pc01:~/webMatters/Ultralight/ultralight-react/build$ cmake --build . --config Release    
    Scanning dependencies of target UltralightSDK
    [  9%] Creating directories for 'UltralightSDK'
    [ 18%] Performing download step (download, verify and extract) for 'UltralightSDK'
    -- Downloading...
       dst='/home/marco/webMatters/Ultralight/ultralight-react/build/UltralightSDK-prefix/src/ultralight-sdk-latest-linux-x64.7z'
       timeout='none'
    -- Using src='https://ultralight-sdk.sfo2.cdn.digitaloceanspaces.com/ultralight-sdk-latest-linux-x64.7z'
    -- [download 0% complete]
    -- [download 1% complete]
    -- [download 2% complete]
    -- [download 3% complete]
    -- [download 4% complete]
    -- [download 5% complete]
    -- [download 6% complete]
    -- [download 7% complete]
    -- [download 8% complete]
    -- [download 9% complete]
    -- [download 10% complete]
    -- [download 11% complete]
    ....
    -- [download 94% complete]
    -- [download 95% complete]
    -- [download 96% complete]
    -- [download 97% complete]
    -- [download 98% complete]
    -- [download 99% complete]
    -- [download 100% complete]
    -- Downloading... done
    -- extracting...
         src='/home/marco/webMatters/Ultralight/ultralight-react/build/UltralightSDK-prefix/src/ultralight-sdk-latest-linux-x64.7z'
         dst='/home/marco/webMatters/Ultralight/ultralight-react/build/SDK'
    -- extracting... [tar xfz]
    -- extracting... [analysis]
    -- extracting... [rename]
    -- extracting... [clean up]
    -- extracting... done
    [ 27%] No patch step for 'UltralightSDK'
    [ 36%] No update step for 'UltralightSDK'
    [ 45%] No configure step for 'UltralightSDK'
    [ 54%] No build step for 'UltralightSDK'
    [ 63%] No install step for 'UltralightSDK'
    [ 72%] Completed 'UltralightSDK'
    [ 72%] Built target UltralightSDK
    Scanning dependencies of target MyApp
    [ 81%] Building CXX object CMakeFiles/MyApp.dir/src/MyApp.cpp.o
    [ 90%] Building CXX object CMakeFiles/MyApp.dir/src/main.cpp.o
    [100%] Linking CXX executable MyApp
    Error copying directory from "/home/marco/webMatters/Ultralight/ultralight-react/app/build/" to "/home/marco/webMatters
    /Ultralight/ultralight-react/build/assets".
    CMakeFiles/MyApp.dir/build.make:98: recipe for target 'MyApp' failed  
    make[2]: *** [MyApp] Error 1
    make[2]: *** Deleting file 'MyApp'
    CMakeFiles/Makefile2:77: recipe for target 'CMakeFiles/MyApp.dir/all' failed
    make[1]: *** [CMakeFiles/MyApp.dir/all] Error 2
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2

- O.S.: Ubuntu 18.04.4 Desktop
- gcc version 9.3.0 (Ubuntu 9.3.0-11ubuntu0~18.04.1)

**Comment by geocine** [comment]
@raphael10-collab 

You error is related to copying
```sh
Error copying directory from "/home/marco/webMatters/Ultralight/ultralight-react/app/build/" to "/home/marco/webMatters
/Ultralight/ultralight-react/build/assets"
```

You could check if its a permission issue, this is the line that does the copying, you can experiment with this command

https://github.com/geocine/ultralight-react/blob/main/cmake/App.cmake#L90

**Comment by raphael10-collab** [comment]
Error copying directory from "/home/marco/webMatters/Ultralight/ultralight-react/app/build/" to "/home/marco/webMatters
    /Ultralight/ultralight-react/build/assets".

    ultralight-react/app$ ls -lah
    total 592K
    drwxr-xr-x    5 marco marco 4,0K feb 23 16:48 .
    drwxr-xr-x    7 marco marco 4,0K feb 23 16:50 ..
    -rw-r--r--    1 marco marco  310 feb 23 16:48 .gitignore
    drwxr-xr-x 1050 marco marco  36K feb 23 16:48 node_modules
    -rw-r--r--    1 marco marco  962 feb 23 16:48 package.json
    drwxr-xr-x    2 marco marco 4,0K feb 23 16:48 public
    drwxr-xr-x    2 marco marco 4,0K feb 23 16:48 src
    -rw-r--r--    1 marco marco  535 feb 23 16:48 tsconfig.json
    -rw-r--r--    1 marco marco 521K feb 23 16:48 yarn.lock


    ultralight-react/build$ ls -lah
    total 77M
    drwxr-xr-x 6 marco marco 4,0K feb 23 16:51 .
    drwxr-xr-x 7 marco marco 4,0K feb 23 16:50 ..
    -rw-r--r-- 1 marco marco  14K feb 23 16:51 CMakeCache.txt
    drwxr-xr-x 7 marco marco 4,0K feb 23 16:51 CMakeFiles
    -rw-r--r-- 1 marco marco 1,6K feb 23 16:51 cmake_install.cmake
    -rw-r--r-- 1 marco marco 645K feb 23 16:51 libAppCore.so
    -rw-r--r-- 1 marco marco 2,2M feb 23 16:51 libUltralightCore.so
    -rw-r--r-- 1 marco marco 605K feb 23 16:51 libUltralight.so
    -rw-r--r-- 1 marco marco  73M feb 23 16:51 libWebCore.so
    -rw-r--r-- 1 marco marco 6,0K feb 23 16:51 Makefile
    drwxr-xr-x 2 marco marco 4,0K feb 23 16:51 resources
    drwxr-xr-x 7 marco marco 4,0K feb 23 16:51 SDK
    drwxr-xr-x 4 marco marco 4,0K feb 23 16:51 UltralightSDK-prefix


I do not see /app/build/ and any /build/assets folders
The folders /app and /build have write permissions

**Comment by geocine** [comment]
@raphael10-collab  Did you build the react app? You need to yun `npm run build` or `yarn build`

**Comment by raphael10-collab** [comment]
@geocine My fault!
I didn't build the react app.

May be I do not understand the workflow: once I modify something in the javascript/react code, I need to `yarn build` -> `build` the app again (`cmake ..` -> `cmake --build . --config Release`) in order to see the changes.
Is it correct, or do I miss something?

**Comment by raphael10-collab** [comment]
One more thing

I opened a multi-window electron app and opened this simple ultralight-react app.
And, to my surprise, seems that the cpu consumption is worse for this ultralight-react-app `MyApp`

![image](https://user-images.githubusercontent.com/70313067/108977000-678f3380-7688-11eb-92fa-1f1f0f37a3a0.png)

And I opened four windows of the electron app : 

![image](https://user-images.githubusercontent.com/70313067/108977410-cb196100-7688-11eb-9d15-51f54a3ae605.png)

**Comment by geocine** [comment]
@raphael10-collab 

Thanks, I don't have an answer for you in that regard, since I am not the maintainer of ultralight. Its best to take this up on the ultralight repository or on discord. This starter is just based on https://github.com/ultralight-ux/ultralight-quick-start

**Comment by raphael10-collab** [comment]
@geocine I'm going to do it in a moment.
Actually I realized it happens also with the simple ultralight-quick-start example: 

![image](https://user-images.githubusercontent.com/70313067/108978948-6f4fd780-768a-11eb-9b82-9087972545da.png)

**Comment by geocine** [comment]
Closing this issue as this is not related to the starter setup , I will update the readme to include the instructions missed out.
